_wandb:
    value:
        cli_version: 0.23.0
        e:
            lkrzb1ew94e54c6erbwr6uef29081bn6:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=55
                    - --worker-launch-time-ms=1764661437838
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "18012913664"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00015
                startedAt: "2025-12-02T07:44:00.747586Z"
                writerId: lkrzb1ew94e54c6erbwr6uef29081bn6
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.2885969467588324
box:
    value: 0.08280612233464707
cls:
    value: 3.576131790360781
copy_paste:
    value: 0.5893323888050034
cutmix:
    value: 0.4186391069380304
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_16-17-18
degrees:
    value: 4.854166519289927
epochs:
    value: 60
fliplr:
    value: 0.13278280470028125
flipud:
    value: 0.07985324827624896
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.06377081314861449
hsv_s:
    value: 0.316155428339544
hsv_v:
    value: 0.6210630791892472
lr0:
    value: 0.03949950797392958
lrf:
    value: 0.8222515031809238
mixup:
    value: 0.5103568977645518
momentum:
    value: 0.6271295709885577
mosaic:
    value: 0.2944837833988184
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0005539975559849105
pid:
    value: 31617
pretrained:
    value: yolo11s.pt
scale:
    value: 0.3851592642777085
shear:
    value: 3.136828623523531
translate:
    value: 0.37674056630905856
trial_id:
    value: 476b5_00015
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00015
warmup_epochs:
    value: 0.7657011533747149
warmup_momentum:
    value: 0.34374583345586235
weight_decay:
    value: 3.342637035172002e-05
