_wandb:
    value:
        cli_version: 0.23.0
        e:
            rg7ml14o7dwj84ov3wz2a4s4k0c0qm7n:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=61
                    - --worker-launch-time-ms=1764663994728
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "18325245952"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00017
                startedAt: "2025-12-02T08:26:37.719509Z"
                writerId: rg7ml14o7dwj84ov3wz2a4s4k0c0qm7n
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.6308390100620889
box:
    value: 0.0912782478940167
cls:
    value: 1.2320088302991214
copy_paste:
    value: 0.8346351177329199
cutmix:
    value: 0.7049540694938701
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_16-45-42
degrees:
    value: 12.899797890569772
epochs:
    value: 60
fliplr:
    value: 0.8582125936988987
flipud:
    value: 0.2187288714771759
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.007685797035758813
hsv_s:
    value: 0.014751238522025246
hsv_v:
    value: 0.7888848779730144
lr0:
    value: 0.04969693927669794
lrf:
    value: 0.704113179106723
mixup:
    value: 0.3355612368085902
momentum:
    value: 0.8677072108701464
mosaic:
    value: 0.6977798560736362
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0007657708816725402
pid:
    value: 33820
pretrained:
    value: yolo11s.pt
scale:
    value: 0.13425381439614933
shear:
    value: 8.926861665619661
translate:
    value: 0.545943113975657
trial_id:
    value: 476b5_00017
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00017
warmup_epochs:
    value: 0.5593167190767473
warmup_momentum:
    value: 0.47462731598188296
weight_decay:
    value: 0.0005776501080923191
