_wandb:
    value:
        cli_version: 0.23.0
        e:
            r3sry0c8jcad5vc948p59bjclkkpz231:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=47
                    - --worker-launch-time-ms=1764659383106
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "17578225664"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00012
                startedAt: "2025-12-02T07:09:46.197506Z"
                writerId: r3sry0c8jcad5vc948p59bjclkkpz231
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.9501292386143309
box:
    value: 0.03827494560694442
cls:
    value: 2.00565326688245
copy_paste:
    value: 0.09666900397547573
cutmix:
    value: 0.502751855090362
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_15-19-10
degrees:
    value: 10.225278659409797
epochs:
    value: 60
fliplr:
    value: 0.2515724140440947
flipud:
    value: 0.6908118101829928
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.035012905040789744
hsv_s:
    value: 0.3004416103808475
hsv_v:
    value: 0.28730084006764334
lr0:
    value: 0.03262988676985138
lrf:
    value: 0.678359959689958
mixup:
    value: 0.2982887731962012
momentum:
    value: 0.8879528978216973
mosaic:
    value: 0.9035298879353394
node_ip:
    value: 172.17.0.4
perspective:
    value: 2.9169196793577434e-05
pid:
    value: 29275
pretrained:
    value: yolo11s.pt
scale:
    value: 0.0035758920568040643
shear:
    value: 6.563889644432183
translate:
    value: 0.14904070985015874
trial_id:
    value: 476b5_00012
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00012
warmup_epochs:
    value: 3.052863340213751
warmup_momentum:
    value: 0.5670165332858684
weight_decay:
    value: 0.0009823660910481652
