_wandb:
    value:
        cli_version: 0.23.0
        e:
            45r77oqhqrhu4d7uhn07uisgcui0mdwy:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=22
                    - --worker-launch-time-ms=1764650586227
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16396476416"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00004
                startedAt: "2025-12-02T04:43:09.542075Z"
                writerId: 45r77oqhqrhu4d7uhn07uisgcui0mdwy
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.6169556015389632
box:
    value: 0.0452204386077916
cls:
    value: 1.7877895567509856
copy_paste:
    value: 0.10229597024465853
cutmix:
    value: 0.5709527509339044
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_13-22-19
degrees:
    value: 41.143037891402855
epochs:
    value: 60
fliplr:
    value: 0.6662069762707699
flipud:
    value: 0.36011139871432674
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.05539801003303022
hsv_s:
    value: 0.24010540653995913
hsv_v:
    value: 0.5848663484027335
lr0:
    value: 0.040662529522509525
lrf:
    value: 0.43935881241852953
mixup:
    value: 0.3706042174666483
momentum:
    value: 0.6105861455353023
mosaic:
    value: 0.7335085260837086
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0006569678605418617
pid:
    value: 21138
pretrained:
    value: yolo11s.pt
scale:
    value: 0.5284911840225717
shear:
    value: 6.990686632945346
translate:
    value: 0.4373313799244794
trial_id:
    value: 476b5_00004
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00004
warmup_epochs:
    value: 3.1488116684713754
warmup_momentum:
    value: 0.5911511651421008
weight_decay:
    value: 0.0007538302801566593
