_wandb:
    value:
        cli_version: 0.23.0
        e:
            wbk8lk2j4sdaz9bbk2qginxt74lc50if:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=53
                    - --worker-launch-time-ms=1764660413512
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "17866018816"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00014
                startedAt: "2025-12-02T07:26:56.908517Z"
                writerId: wbk8lk2j4sdaz9bbk2qginxt74lc50if
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.5096711274109408
box:
    value: 0.030814977588203812
cls:
    value: 1.9538651162497738
copy_paste:
    value: 0.6920021739758906
cutmix:
    value: 0.20489176717457547
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_15-43-55
degrees:
    value: 6.120457905381163
epochs:
    value: 60
fliplr:
    value: 0.03942190566318149
flipud:
    value: 0.04777304167062091
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.010848608372738723
hsv_s:
    value: 0.20325651143679566
hsv_v:
    value: 0.8653443141553475
lr0:
    value: 0.06354676673264059
lrf:
    value: 0.26343218227317794
mixup:
    value: 0.33313282269013833
momentum:
    value: 0.8475334310837528
mosaic:
    value: 0.8672203377609379
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.00033637378663249005
pid:
    value: 30668
pretrained:
    value: yolo11s.pt
scale:
    value: 0.8715341162796342
shear:
    value: 8.79142662879971
translate:
    value: 0.7301562431220718
trial_id:
    value: 476b5_00014
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00014
warmup_epochs:
    value: 3.273148777782332
warmup_momentum:
    value: 0.2967025533645377
weight_decay:
    value: 0.0002580862591130434
