_wandb:
    value:
        cli_version: 0.23.0
        e:
            9osr6ck30vq3idwa8baz3zz61gw4z5z1:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=17
                    - --worker-launch-time-ms=1764649063917
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16103964672"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00002
                startedAt: "2025-12-02T04:17:47.455878Z"
                writerId: 9osr6ck30vq3idwa8baz3zz61gw4z5z1
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.994349294286733
box:
    value: 0.16409718893121159
cls:
    value: 2.610358944805085
copy_paste:
    value: 0.1485003208653315
cutmix:
    value: 0.718328887452846
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_12-35-09
degrees:
    value: 7.797617635504846
epochs:
    value: 60
fliplr:
    value: 0.4562769016644862
flipud:
    value: 0.6949636623713269
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.074823074197637
hsv_s:
    value: 0.3417248412027065
hsv_v:
    value: 0.3876966313172086
lr0:
    value: 0.047375364637236655
lrf:
    value: 0.5148452740859218
mixup:
    value: 0.9170780438439402
momentum:
    value: 0.7359373602768224
mosaic:
    value: 0.4339850118184593
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0005849621658982906
pid:
    value: 19500
pretrained:
    value: yolo11s.pt
scale:
    value: 0.5713726837410619
shear:
    value: 6.006187858676252
translate:
    value: 0.7935892975727818
trial_id:
    value: 476b5_00002
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00002
warmup_epochs:
    value: 1.0165559234433568
warmup_momentum:
    value: 0.8780862079026729
weight_decay:
    value: 0.0005315190925525319
