_wandb:
    value:
        cli_version: 0.23.0
        e:
            p053a5ezw8wvsexz6uagsyc35ibxzhaz:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=43
                    - --worker-launch-time-ms=1764658906959
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "17434431488"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00011
                startedAt: "2025-12-02T07:01:50.592125Z"
                writerId: p053a5ezw8wvsexz6uagsyc35ibxzhaz
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.06266666951772737
box:
    value: 0.1762486788502974
cls:
    value: 2.610185627066239
copy_paste:
    value: 0.9479116808114093
cutmix:
    value: 0.141673610942462
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_15-09-41
degrees:
    value: 40.849877565086935
epochs:
    value: 60
fliplr:
    value: 0.6105039394200683
flipud:
    value: 0.37800408328574453
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.0680590127507966
hsv_s:
    value: 0.5579993261349055
hsv_v:
    value: 0.15017514677975197
lr0:
    value: 0.09673051806004779
lrf:
    value: 0.9592690167651274
mixup:
    value: 0.07489688746264145
momentum:
    value: 0.920380276589021
mosaic:
    value: 0.13895144925827363
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0005730444995258673
pid:
    value: 28605
pretrained:
    value: yolo11s.pt
scale:
    value: 0.09205949178466548
shear:
    value: 4.325296195568921
translate:
    value: 0.2501423847290501
trial_id:
    value: 476b5_00011
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00011
warmup_epochs:
    value: 2.125029948276591
warmup_momentum:
    value: 0.7629871973359114
weight_decay:
    value: 3.250118499520927e-05
