_wandb:
    value:
        cli_version: 0.23.0
        e:
            omqj4p6r3hy3fxxnsok2jmzl6dzoufop:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=26
                    - --worker-launch-time-ms=1764652942305
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16552374272"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00005
                startedAt: "2025-12-02T05:22:25.848861Z"
                writerId: omqj4p6r3hy3fxxnsok2jmzl6dzoufop
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.7856458602097159
box:
    value: 0.04587624584834512
cls:
    value: 3.231315980253611
copy_paste:
    value: 0.8961724023572124
cutmix:
    value: 0.6546838315708874
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_13-28-38
degrees:
    value: 29.6306904548422
epochs:
    value: 60
fliplr:
    value: 0.15612529765131244
flipud:
    value: 0.09567568618318545
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.006665920434694473
hsv_s:
    value: 0.6063572335085602
hsv_v:
    value: 0.4799787195164311
lr0:
    value: 0.03418535111540756
lrf:
    value: 0.9701469737243997
mixup:
    value: 0.3220873907316042
momentum:
    value: 0.7529311252130191
mosaic:
    value: 0.2055996514641356
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0008968848099716482
pid:
    value: 22800
pretrained:
    value: yolo11s.pt
scale:
    value: 0.8148173853344679
shear:
    value: 3.6430544827934574
translate:
    value: 0.0698147898421665
trial_id:
    value: 476b5_00005
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00005
warmup_epochs:
    value: 1.6644684557590583
warmup_momentum:
    value: 0.3721274547242509
weight_decay:
    value: 0.0005513561003300996
