_wandb:
    value:
        cli_version: 0.23.0
        e:
            bov39f4he0dtr2h1pl6uw0jah3rjr1f4:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=34
                    - --worker-launch-time-ms=1764655733873
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16993734656"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00008
                startedAt: "2025-12-02T06:08:56.839603Z"
                writerId: bov39f4he0dtr2h1pl6uw0jah3rjr1f4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.7588031308156631
box:
    value: 0.19438276594680357
cls:
    value: 3.9256044441671913
copy_paste:
    value: 0.7999169936618109
cutmix:
    value: 0.8454005498516156
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_14-24-16
degrees:
    value: 20.833071975816207
epochs:
    value: 60
fliplr:
    value: 0.7751108490080462
flipud:
    value: 0.5611694784869895
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.03752923093634774
hsv_s:
    value: 0.5101342873939019
hsv_v:
    value: 0.845334908718087
lr0:
    value: 0.08673286611247795
lrf:
    value: 0.9883036408820378
mixup:
    value: 0.1290189822766794
momentum:
    value: 0.6224372268510778
mosaic:
    value: 0.9154516125758756
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0005012889584933874
pid:
    value: 25539
pretrained:
    value: yolo11s.pt
scale:
    value: 0.6378858374584934
shear:
    value: 4.724668737265959
translate:
    value: 0.8527753068966117
trial_id:
    value: 476b5_00008
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00008
warmup_epochs:
    value: 2.1616851976868268
warmup_momentum:
    value: 0.05035030925879539
weight_decay:
    value: 0.00010685340656727671
