_wandb:
    value:
        cli_version: 0.23.0
        e:
            zr0bxepwx1xalvkbv5m0bqjadum2y92j:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=29
                    - --worker-launch-time-ms=1764653321104
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "16696823808"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00006
                startedAt: "2025-12-02T05:28:44.204894Z"
                writerId: zr0bxepwx1xalvkbv5m0bqjadum2y92j
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.3299301269095364
box:
    value: 0.06562997686868169
cls:
    value: 3.5848365294782107
copy_paste:
    value: 0.19096703856273478
cutmix:
    value: 0.03157677013334792
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_13-35-47
degrees:
    value: 44.8204134587045
epochs:
    value: 60
fliplr:
    value: 0.18122863563861213
flipud:
    value: 0.8699135636299012
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.03461673317624159
hsv_s:
    value: 0.6996730849413761
hsv_v:
    value: 0.6405784167704541
lr0:
    value: 0.04733798632463429
lrf:
    value: 0.36429541178457764
mixup:
    value: 0.4257062526290213
momentum:
    value: 0.6363009800614593
mosaic:
    value: 0.8468745029848809
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0008054139714731305
pid:
    value: 23426
pretrained:
    value: yolo11s.pt
scale:
    value: 0.419213943006707
shear:
    value: 9.055161370293233
translate:
    value: 0.6936074498150022
trial_id:
    value: 476b5_00006
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00006
warmup_epochs:
    value: 2.8076028577946683
warmup_momentum:
    value: 0.634972632882196
weight_decay:
    value: 0.0009678628331793324
