_wandb:
    value:
        cli_version: 0.23.0
        e:
            zgq2pw1gdrsopy8uuu0zjnofsnew2lsg:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=50
                    - --worker-launch-time-ms=1764659953363
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "17719717888"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00013
                startedAt: "2025-12-02T07:19:16.317675Z"
                writerId: zgq2pw1gdrsopy8uuu0zjnofsnew2lsg
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.7014444285935184
box:
    value: 0.16528090046571853
cls:
    value: 1.2171622695431927
copy_paste:
    value: 0.07387515671446576
cutmix:
    value: 0.3615473707288406
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_15-26-51
degrees:
    value: 10.499311023259853
epochs:
    value: 60
fliplr:
    value: 0.25080246729575106
flipud:
    value: 0.26322952186644
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.0488855121557249
hsv_s:
    value: 0.17245525816893792
hsv_v:
    value: 0.7361490304631519
lr0:
    value: 0.019678959545234624
lrf:
    value: 0.616737716155813
mixup:
    value: 0.21966349471452717
momentum:
    value: 0.8265206533649956
mosaic:
    value: 0.9966398361022459
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.0009042470826036973
pid:
    value: 30003
pretrained:
    value: yolo11s.pt
scale:
    value: 0.7780587588797963
shear:
    value: 2.7359219812098456
translate:
    value: 0.8140472644294567
trial_id:
    value: 476b5_00013
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00013
warmup_epochs:
    value: 0.5981221169509493
warmup_momentum:
    value: 0.8939329971385618
weight_decay:
    value: 4.995573656637908e-05
