_wandb:
    value:
        cli_version: 0.23.0
        e:
            sjg7lt5yh09vzdeo2pwunhnnteweh3v5:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=65
                    - --worker-launch-time-ms=1764665145055
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "18459033600"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00018
                startedAt: "2025-12-02T08:45:47.976524Z"
                writerId: sjg7lt5yh09vzdeo2pwunhnnteweh3v5
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.30668437998832176
box:
    value: 0.03865475852970274
cls:
    value: 3.112836931897213
copy_paste:
    value: 0.2107930093543764
cutmix:
    value: 0.9924498078963911
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_16-53-50
degrees:
    value: 26.626787818646342
epochs:
    value: 60
fliplr:
    value: 0.17948799238303392
flipud:
    value: 0.2806800277597916
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.0496756162112996
hsv_s:
    value: 0.06479421592752059
hsv_v:
    value: 0.6703136681960984
lr0:
    value: 0.057218078132175845
lrf:
    value: 0.7956917904233685
mixup:
    value: 0.09682295997119639
momentum:
    value: 0.8815827140923651
mosaic:
    value: 0.5359761534922229
node_ip:
    value: 172.17.0.4
perspective:
    value: 6.729630223410432e-05
pid:
    value: 34839
pretrained:
    value: yolo11s.pt
scale:
    value: 0.6973760691588734
shear:
    value: 9.000545459577888
translate:
    value: 0.27715023179280707
trial_id:
    value: 476b5_00018
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00018
warmup_epochs:
    value: 1.5814202193133098
warmup_momentum:
    value: 0.3217195464347806
weight_decay:
    value: 0.00039465430193627284
