_wandb:
    value:
        cli_version: 0.23.0
        e:
            bfbwpyx3w9bq6volmhuunobxo51467ju:
                args:
                    - --node-ip-address=172.17.0.4
                    - --node-manager-port=44831
                    - --object-store-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-12-02_11-23-28_642637_15770/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63426
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=57271
                    - --gcs-address=172.17.0.4:64223
                    - --session-name=session_2025-12-02_11-23-28_642637_15770
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=403d16d8ec868cc7f00b1f4771b2d9b2218a81b5d6af9e311ba9f93b
                    - --startup-token=37
                    - --worker-launch-time-ms=1764656658328
                    - --node-id=17de6c4364b00df7af153eb511c4bd698bdc31a23c0bbed0f520c8f2
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "17137037312"
                email: Louise158@stu.sufe.edu.cn
                executable: /root/miniconda3/envs/yolo11/bin/python
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-26def0a3-b7bf-ffc8-a4a0-062c8c700c28
                host: autodl-container-bfc840bf61-9a26cdb5
                memory:
                    total: "472735358976"
                os: Linux-5.4.0-163-generic-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/yolo11/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.0
                root: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00009
                startedAt: "2025-12-02T06:24:21.264684Z"
                writerId: bfbwpyx3w9bq6volmhuunobxo51467ju
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 30
            "2":
                - 30
            "3":
                - 2
                - 13
                - 14
                - 16
                - 19
                - 61
            "4": 3.12.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
bgr:
    value: 0.1979395514059049
box:
    value: 0.12416069424448375
cls:
    value: 2.878813860164093
copy_paste:
    value: 0.6055992356950315
cutmix:
    value: 0.1879747891032354
data:
    value: /root/yolo11/roboflow_dataset/data.yaml
date:
    value: 2025-12-02_14-54-40
degrees:
    value: 2.3814492145879984
epochs:
    value: 60
fliplr:
    value: 0.9803921611687463
flipud:
    value: 0.6609153565200385
hostname:
    value: autodl-container-bfc840bf61-9a26cdb5
hsv_h:
    value: 0.08814251509519555
hsv_s:
    value: 0.36106852855364846
hsv_v:
    value: 0.345207974152137
lr0:
    value: 0.06115535838530294
lrf:
    value: 0.6404796287603038
mixup:
    value: 0.740382856323706
momentum:
    value: 0.9030509794587951
mosaic:
    value: 0.4799490872661105
node_ip:
    value: 172.17.0.4
perspective:
    value: 0.00042694189164116516
pid:
    value: 26589
pretrained:
    value: yolo11s.pt
scale:
    value: 0.31569586079035683
shear:
    value: 9.264375718813824
translate:
    value: 0.0417213873421477
trial_id:
    value: 476b5_00009
trial_log_path:
    value: /tmp/ray/session_2025-12-02_11-23-28_642637_15770/artifacts/2025-12-02_11-23-32/tune_yolo11s_run1/driver_artifacts/_tune_476b5_00009
warmup_epochs:
    value: 4.569463145943824
warmup_momentum:
    value: 0.0416360210317251
weight_decay:
    value: 0.0009349114667871281
